#!/usr/bin/env python

import optparse

from tornado import ioloop

from APNsPushService import APNsPushService

parser = optparse.OptionParser()

parser.add_option("-c", "--cert-file",
                  dest="cert_file",
                    help="Path to .pem certificate file")

parser.add_option("-k", "--key-file",
                  dest="key_file",
                    help="Path to .pem key file")

options, args = parser.parse_args()

if options.cert_file is None:
    parser.error('Must provide --cert-file')

if options.key_file is None:
    parser.error('Must provide --key-file')


test_server = APNsPushService(cert_file=options.cert_file,
                                    key_file=options.key_file,
                                )

test_server.listen(2195)

ioloop.IOLoop.instance().start()


