#!/usr/bin/env python

import optparse

from tornado import ioloop

from APNsFeedBackService import APNsFeedBackService

parser = optparse.OptionParser()

parser.add_option("-c", "--cert-file",
                  dest="cert_file",
                    help="Path to .pem certificate file")

parser.add_option("-k", "--key-file",
                  dest="key_file",
                    help="Path to .pem key file")

parser.add_option("-n", "--data-num",
                  dest="data_num",
                    help="Feedback data num")

options, args = parser.parse_args()

if options.cert_file is None:
    parser.error('Must provide --cert-file')

if options.key_file is None:
    parser.error('Must provide --key-file')

if options.data_num is None:
    parser.error('Must provide --data-num')


test_server = APNsFeedBackService(cert_file=options.cert_file,
                                    key_file=options.key_file,
                                    data_num=int(options.data_num))

test_server.listen(2196)

ioloop.IOLoop.instance().start()


